import { useEffect, useMemo, useState, type FormEvent } from "react"
import { Combine, Search } from "lucide-react"

import { DetalleUnidadPrestamo } from "@/components/prestamos/detalle-unidad-prestamo"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { type Combinada, type CombinadaFormValues } from "@/lib/combinadas"
import {
  UNIDAD_ESTADO_PRESTADA,
  type HerramientaUnidad,
} from "@/lib/herramientas"
import { filtrarUnidadesPorBusqueda, nombreUnidad } from "@/lib/prestamos"

export type CombinadaFieldErrors = {
  nombre?: string
  descripcion?: string
  unidades_ids?: string
}

type ModalCombinadaProps = {
  open: boolean
  item?: Combinada | null
  unidades: HerramientaUnidad[]
  isLoadingUnidades?: boolean
  isSubmitting: boolean
  formError: string
  fieldErrors: CombinadaFieldErrors
  onOpenChange: (open: boolean) => void
  onSubmit: (values: CombinadaFormValues) => void
}

export function ModalCombinada({
  open,
  item,
  unidades,
  isLoadingUnidades = false,
  isSubmitting,
  formError,
  fieldErrors,
  onOpenChange,
  onSubmit,
}: ModalCombinadaProps) {
  const isEditing = Boolean(item)
  const [nombre, setNombre] = useState("")
  const [usarNombrePersonalizado, setUsarNombrePersonalizado] = useState(false)
  const [search, setSearch] = useState("")
  const [selectedIds, setSelectedIds] = useState<string[]>([])
  const [localErrors, setLocalErrors] = useState<CombinadaFieldErrors>({})

  const selectedUnits = useMemo(
    () =>
      selectedIds
        .map((id) => unidades.find((unidad) => unidad.id === id))
        .filter((unidad): unidad is HerramientaUnidad => Boolean(unidad)),
    [selectedIds, unidades],
  )

  const autoNombre = useMemo(
    () =>
      selectedUnits.length > 0
        ? selectedUnits.map((unidad) => nombreUnidad(unidad)).join(" + ")
        : "",
    [selectedUnits],
  )

  useEffect(() => {
    if (!open) return

    const initialIds = (item?.unidades ?? []).map((unidad) => unidad.id)
    const initialUnits = initialIds
      .map((id) => unidades.find((u) => u.id === id))
      .filter((u): u is HerramientaUnidad => Boolean(u))

    const autoGeneratedName = initialUnits
      .map((unidad) => nombreUnidad(unidad))
      .join(" + ")

    const hasCustomName = Boolean(item?.nombre && item.nombre !== autoGeneratedName)

    setNombre(item?.nombre ?? "")
    setUsarNombrePersonalizado(hasCustomName)
    setSearch("")
    setSelectedIds(initialIds)
    setLocalErrors({})
  }, [item, open, unidades])

  const filteredUnits = useMemo(
    () => filtrarUnidadesPorBusqueda(unidades, search),
    [unidades, search],
  )

  const closeModal = () => {
    if (isSubmitting) return
    onOpenChange(false)
  }

  const toggleUnit = (unidadId: string, checked: boolean) => {
    setSelectedIds((current) =>
      checked
        ? [...current, unidadId]
        : current.filter((selectedId) => selectedId !== unidadId),
    )
    setLocalErrors((current) => ({
      ...current,
      unidades_ids: undefined,
      nombre: undefined,
    }))
  }

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    const nextErrors: CombinadaFieldErrors = {}
    const finalNombre = usarNombrePersonalizado ? nombre.trim() : autoNombre

    if (!finalNombre) {
      nextErrors.nombre = usarNombrePersonalizado
        ? "Escribe un nombre para el conjunto."
        : "Selecciona al menos dos unidades para generar el nombre."
    }

    if (selectedIds.length < 2) {
      nextErrors.unidades_ids = "Selecciona al menos dos unidades."
    }

    if (Object.keys(nextErrors).length > 0) {
      setLocalErrors(nextErrors)
      return
    }

    onSubmit({
      nombre: finalNombre,
      descripcion: "",
      unidades_ids: selectedIds,
    })
  }

  const shownErrors: CombinadaFieldErrors = {
    nombre: localErrors.nombre || fieldErrors.nombre,
    unidades_ids: localErrors.unidades_ids || fieldErrors.unidades_ids,
  }
  const firstFieldError = Object.values(shownErrors).find(Boolean) ?? ""
  const shownFormError =
    formError && formError !== firstFieldError ? formError : ""

  return (
    <Dialog
      open={open}
      onOpenChange={(nextOpen) => {
        if (!nextOpen) {
          closeModal()
          return
        }

        onOpenChange(true)
      }}
    >
      <DialogContent className="flex h-[min(86vh,48rem)] w-[min(92vw,68rem)] max-w-none flex-col gap-4 overflow-hidden p-5 sm:max-w-none">
        <DialogHeader className="gap-2">
          <DialogTitle className="pr-10 text-xl font-semibold tracking-tight">
            {isEditing ? "Editar combinada" : "Agregar combinada"}
          </DialogTitle>
        </DialogHeader>

        <form
          id="combinada-form"
          className="flex min-h-0 flex-1 flex-col gap-4"
          onSubmit={handleSubmit}
          noValidate
        >
          {shownFormError ? (
            <div
              className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"
              role="alert"
            >
              {shownFormError}
            </div>
          ) : null}

          {/* Campo de Nombre con Checkbox opcional de personalización */}
          <div className="space-y-0.5">
            <div className="flex items-center justify-between gap-2">
              <label
                htmlFor="combinada-nombre"
                className="text-sm font-medium"
              >
                Nombre del conjunto
              </label>

              <label className="flex cursor-pointer items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground">
                <Checkbox
                  className="size-4"
                  checked={usarNombrePersonalizado}
                  disabled={isSubmitting}
                  onCheckedChange={(checked) => {
                    const isCustom = checked === true
                    setUsarNombrePersonalizado(isCustom)
                    if (isCustom) {
                      setNombre(autoNombre)
                    } else {
                      setNombre("")
                    }
                  }}
                />
                <span>Personalizar nombre</span>
              </label>
            </div>

            {usarNombrePersonalizado ? (
              <Input
                id="combinada-nombre"
                className="h-9 text-sm"
                placeholder="Ej. Llave de bujía especial"
                value={nombre}
                disabled={isSubmitting}
                aria-invalid={Boolean(shownErrors.nombre)}
                onChange={(event) => {
                  setNombre(event.target.value)
                  if (localErrors.nombre) {
                    setLocalErrors((current) => ({
                      ...current,
                      nombre: undefined,
                    }))
                  }
                }}
              />
            ) : (
              <div className="flex h-9 min-w-0 items-center rounded-lg border border-amber-400/50 bg-amber-400/10 px-3 text-sm font-medium text-amber-900 shadow-xs dark:border-amber-300/50 dark:bg-amber-400/15 dark:text-amber-200">
                <Combine className="mr-2 size-4 shrink-0 text-amber-600 dark:text-amber-300" />
                <span className="truncate">
                  {autoNombre || (
                    <span className="font-normal italic text-amber-700/80 dark:text-amber-300/70">
                      El nombre se generará automáticamente con las unidades seleccionadas...
                    </span>
                  )}
                </span>
              </div>
            )}

            {shownErrors.nombre ? (
              <p className="text-sm text-destructive">{shownErrors.nombre}</p>
            ) : null}
          </div>

          {/* Buscador de unidades */}
          <div className="relative">
            <label htmlFor="combinada-search" className="sr-only">
              Buscar unidad
            </label>
            <Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              id="combinada-search"
              className="h-10 pl-9"
              placeholder="Buscar por herramienta, marca o ubicación..."
              value={search}
              disabled={isSubmitting}
              onChange={(event) => setSearch(event.target.value)}
            />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2 text-sm">
            <span className="font-medium">Unidades del conjunto</span>
            <span className="text-muted-foreground">
              {selectedIds.length} seleccionadas
            </span>
          </div>

          {shownErrors.unidades_ids ? (
            <p className="text-sm text-destructive">
              {shownErrors.unidades_ids}
            </p>
          ) : null}

          {isLoadingUnidades ? (
            <div className="flex flex-1 items-center justify-center rounded-xl border border-dashed py-16 text-center text-base text-muted-foreground">
              Cargando unidades...
            </div>
          ) : filteredUnits.length > 0 ? (
            <div className="min-h-0 flex-1 space-y-3 overflow-y-auto pr-1">
              {filteredUnits.map((unidad) => {
                const isSelected = selectedIds.includes(unidad.id)
                const estaPrestada = unidad.estado === UNIDAD_ESTADO_PRESTADA

                return (
                  <label
                    key={unidad.id}
                    className="flex cursor-pointer items-center gap-3 rounded-xl border p-3 transition-colors hover:bg-muted/50 has-data-checked:border-primary has-data-checked:bg-muted/50"
                  >
                    <Checkbox
                      className="size-4"
                      checked={isSelected}
                      disabled={isSubmitting}
                      onCheckedChange={(checked) =>
                        toggleUnit(unidad.id, checked === true)
                      }
                    />
                    <div className="min-w-0 flex-1">
                      <p className="flex items-center gap-2 truncate text-base font-medium">
                        {nombreUnidad(unidad)}
                        {estaPrestada ? (
                          <span className="inline-flex rounded-full bg-amber-500/15 px-2 py-0.5 text-xs font-medium text-amber-700 dark:text-amber-300">
                            Prestada
                          </span>
                        ) : null}
                      </p>
                      <DetalleUnidadPrestamo
                        unidad={unidad}
                        className="mt-0.5 text-sm"
                      />
                    </div>
                  </label>
                )
              })}
            </div>
          ) : (
            <div className="flex flex-1 flex-col items-center justify-center rounded-xl border border-dashed py-16 text-center">
              <p className="text-lg font-medium">No hay unidades para mostrar</p>
              <p className="mt-2 text-base text-muted-foreground">
                Prueba con otra búsqueda o registra primero las herramientas.
              </p>
            </div>
          )}
        </form>

        <DialogFooter className="-mx-5 -mb-5 mt-auto p-5 pt-2.5 pb-2.5">
          <Button
            type="button"
            variant="outline"
            size="lg"
            className="h-9"
            disabled={isSubmitting}
            onClick={closeModal}
          >
            Cancelar
          </Button>
          <Button
            type="submit"
            form="combinada-form"
            size="lg"
            className="h-9"
            disabled={isSubmitting || isLoadingUnidades}
          >
            {isSubmitting ? "Guardando..." : "Guardar"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
